package fr.layttos.utils;

public enum ActionBuilderEvent {

    INVENTORY_CLICK_EVENT,
    PLAYER_DROP_ITEM_EVENT,
    PLAYER_PICKUP_ITEM_EVENT,
    PLAYER_INTERACT_EVENT,
    PLAYER_SWITCH_SLOT_EVENT,
    PLAYER_CONSUME_ITEM_EVENT,
    PLAYER_BREAKS_BLOCK_WHILE_HANDLING_ITEM,
    PLAYER_FISH_EVENT,
    CRAFT_ITEM_EVENT,
    PLAYER_INTERACT_TO_ENTITY_EVENT,
    ;

}
